language: java
rvm:
 - 2.2
 <?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.maximelefrancois86</groupId>
    <artifactId>i2si-maven-tutorial</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
       
    <name>Tutorial for Maven</name>
    <description>Simple project for the MINES Saint-Etienne I2SI course</description>
    <url>http://github.com/maximelefrancois86/i2si-maven-tutorial</url>
    <inceptionYear>2018</inceptionYear>

    <prerequisites>
        <maven>3.0.3</maven>
    </prerequisites>

    <developers>
        <developer>
            <name>Maxime Lefrançois</name>            
            <email>maxime.lefrancois@emse.fr</email>
            <url>http://maxime-lefrancois.info/</url>
            <organization>Ecole des mines de Saint-Etienne</organization>
            <organizationUrl>http://www.mines-stetienne.fr/</organizationUrl>
            <timezone>UTC+01:00</timezone>
            <properties>
                <picUrl>http://gravatar.com/userimage/102097381/dac8aeb15edac9a93e09a7974743957f</picUrl>
            </properties>        
        </developer>
    </developers>

    <organization>
        <name>École des Mines de Saint-Étienne</name>
        <url>http://www.mines-stetienne.fr/</url>
    </organization>

    <scm>
        <connection>scm:git:https://${repository.domain}/${repository.user}/${repository.name}.git</connection>
        <url>https://${repository.domain}/${repository.user}/${repository.name}</url>
        <developerConnection>scm:git:https://${repository.domain}/${repository.user}/${repository.name}.git
        </developerConnection>
    </scm>
    
    <issueManagement>
        <url>http://${repository.domain}/${repository.user}/${repository.name}/issues</url>
        <system>GitHub Issues</system>
    </issueManagement>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ssZ</maven.build.timestamp.format>
        <jdk.version>1.8</jdk.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>        
        <project.scm.id>git</project.scm.id>
        <repository.domain>github.com</repository.domain>
        <repository.user>maximelefrancois86</repository.user>
        <repository.name>i2si-maven-tutorial</repository.name>
    </properties>
    
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.0</version>
            <type>jar</type>
        </dependency>
    </dependencies>
  
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.7.1</version>
                <configuration>
                    <skipDeploy>true</skipDeploy>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.0.0</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>summary</report>
                            <report>team</report>
                            <report>licenses</report>
                            <report>scm</report> 
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>javadoc</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>        
        </plugins>
    </reporting>
    
</project>
 - java
